DataPreprocessor:
    dataset: sign_mnist_train
MLModel:
    dense:
    - 128
    - 64
    epochs: 100
    filters:
    - 32
    - 64
data_preprocess_test:
    dataset: sign_mnist_test
download_kaggle:
    dataset: datamunge/sign-language-mnist
