DataPreprocessor:
  dataset: sign_mnist_train
MLModel:
  dense:
  - 32
  epochs: 3
  filters:
  - 32
  - 32
data_preprocess_test:
  dataset: sign_mnist_test
download_kaggle:
  dataset: datamunge/sign-language-mnist
