DataPreprocessor:
    dataset: sign_mnist_train
MLModel:
    dense:
    - 4
    epochs: 5
    filters:
    - 2
data_preprocess_test:
    dataset: sign_mnist_test
download_kaggle:
    dataset: datamunge/sign-language-mnist
