DataPreprocessor:
  dataset: sign_mnist_train
MLModel:
  dense:
  - 128
  - 64
  - 32
  epochs: 20
  filters: []
  optimizer: adam
download_kaggle:
  dataset: datamunge/sign-language-mnist
test_data:
  dataset: sign_mnist_test
