DataPreprocessor:
    dataset: sign_mnist_train
MLModel:
    dense:
    - 8
    epochs: 10
    filters:
    - 4
    optimizer: adam
download_kaggle:
    dataset: datamunge/sign-language-mnist
test_data:
    dataset: sign_mnist_test
