DataPreprocessor:
    dataset: sign_mnist_train
MLModel:
    dense:
    - 16
    epochs: 5
    filters:
    - 8
    - 8
data_preprocess_test:
    dataset: sign_mnist_test
download_kaggle:
    dataset: datamunge/sign-language-mnist
